---
- name: Install Wordpress, PostgresQL and apache2
  hosts: deployment
  remote_user: serhiy
  become_user: root
  become_method: sudo

  vars_files:
    - group_vars/main.yml

  roles:
    - postgresql
    - apache2
    - wordpress
    - iptables